
default_platform(:android)

platform :android do
  desc "Lane for android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sleep(10)
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons",
    firebase_app_distribution(
    app: "1:293896661413:android:11505809681cbb4cf7604c",
    firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
    
    apk_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "haithamwajdi02@gmail.com",
    release_notes:"ya rab"
    )
  end

end
